# Generated by Django 4.2.5 on 2023-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="date_of_birth",
        ),
    ]
