# Generated by Django 4.2.5 on 2023-10-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0002_remove_teacher_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
        migrations.AddField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(to="subject.teacher"),
        ),
    ]
