# Generated by Django 4.2.5 on 2023-10-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0003_remove_subject_teachers_subject_teachers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subject.subject",
            ),
        ),
    ]
