# Generated by Django 4.2.5 on 2023-10-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0004_remove_subject_teachers_teacher_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(blank=True, null=True, to="subject.subject"),
        ),
    ]
