# Generated by Django 4.2.5 on 2023-11-30 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_remove_teacher_subject_teacher_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="subject",
        ),
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subject.teacher",
            ),
        ),
    ]
