# Generated by Django 4.2.5 on 2023-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
    ]
