# Generated by Django 4.2.5 on 2023-10-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
        ("students", "0002_alter_student_absences_alter_student_grades_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="absences",
        ),
        migrations.RemoveField(
            model_name="student",
            name="grades",
        ),
        migrations.RemoveField(
            model_name="student",
            name="notes",
        ),
        migrations.AddField(
            model_name="student",
            name="absences",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.absence",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grades",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subject.grade",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="notes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.note",
            ),
        ),
    ]
