# Generated by Django 4.2.5 on 2023-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_remove_student_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="student",
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ManyToManyField(blank=True, null=True, to="students.student"),
        ),
    ]
