# Generated by Django 4.2.5 on 2023-10-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
        ("students", "0003_remove_student_absences_remove_student_grades_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="absences",
        ),
        migrations.RemoveField(
            model_name="student",
            name="grades",
        ),
        migrations.RemoveField(
            model_name="student",
            name="notes",
        ),
        migrations.AddField(
            model_name="absence",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
                    ),
                ),
                ("date", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subject.subject",
                    ),
                ),
            ],
        ),
    ]
