# Generated by Django 4.2.5 on 2023-11-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_remove_teacher_subject_teacher_subject"),
        ("students", "0003_remove_grade_student_grade_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="student",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="subject",
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ManyToManyField(blank=True, null=True, to="subject.subject"),
        ),
    ]
