# Generated by Django 4.2.5 on 2023-11-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0005_remove_teacher_subject_teacher_subject"),
        ("students", "0004_remove_grade_student_remove_grade_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="subject",
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subject.subject",
            ),
        ),
    ]
