# Generated by Django 4.2.5 on 2023-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="event_img"),
                ),
                ("description", models.TextField()),
            ],
        ),
    ]
