# Generated by Django 4.2.5 on 2023-10-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_teachers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="last_name",
        ),
    ]
