# Generated by Django 4.2.5 on 2023-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_teachers", "0002_remove_appuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
