# Generated by Django 4.2.5 on 2023-10-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_teachers", "0003_appuser_date_of_birth_appuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="date_of_birth",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
