# Generated by Django 4.2.5 on 2023-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_teachers", "0004_alter_appuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="date_of_birth",
        ),
    ]
